export interface MetricVariable { key: string; label: string; scope: 'team' | 'player' }

export const TEAM_VARIABLES: MetricVariable[] = [
  { key: 'matches_played', label: 'Matches Played', scope: 'team' },
  { key: 'wins', label: 'Wins', scope: 'team' },
  { key: 'draws', label: 'Draws', scope: 'team' },
  { key: 'losses', label: 'Losses', scope: 'team' },
  { key: 'points', label: 'Points', scope: 'team' },
  { key: 'goals_for', label: 'Goals For', scope: 'team' },
  { key: 'goals_against', label: 'Goals Against', scope: 'team' },
  { key: 'goal_difference', label: 'Goal Difference', scope: 'team' },
  { key: 'win_rate', label: 'Win Rate', scope: 'team' },
  { key: 'draw_rate', label: 'Draw Rate', scope: 'team' },
  { key: 'loss_rate', label: 'Loss Rate', scope: 'team' },
  { key: 'goals_for_per_match', label: 'Goals For / Match', scope: 'team' },
  { key: 'goals_against_per_match', label: 'Goals Against / Match', scope: 'team' },
  { key: 'clean_sheets', label: 'Clean Sheets', scope: 'team' },
  { key: 'failed_to_score', label: 'Failed to Score', scope: 'team' },
  { key: 'home_wins', label: 'Home Wins', scope: 'team' },
  { key: 'away_wins', label: 'Away Wins', scope: 'team' },
  { key: 'shots_on_goal', label: 'Shots on Goal', scope: 'team' },
  { key: 'total_shots', label: 'Total Shots', scope: 'team' },
  { key: 'fouls', label: 'Fouls', scope: 'team' },
  { key: 'corner_kicks', label: 'Corner Kicks', scope: 'team' },
  { key: 'yellow_cards', label: 'Yellow Cards', scope: 'team' },
  { key: 'red_cards', label: 'Red Cards', scope: 'team' },
  { key: 'possession', label: 'Possession %', scope: 'team' },
  { key: 'pass_accuracy', label: 'Pass Accuracy %', scope: 'team' },
  { key: 'expected_goals', label: 'Expected Goals (xG)', scope: 'team' },
];

export const PLAYER_VARIABLES: MetricVariable[] = [
  { key: 'appearances', label: 'Appearances', scope: 'player' },
  { key: 'minutes', label: 'Minutes Played', scope: 'player' },
  { key: 'rating', label: 'Rating', scope: 'player' },
  { key: 'goals', label: 'Goals', scope: 'player' },
  { key: 'assists', label: 'Assists', scope: 'player' },
  { key: 'shots_total', label: 'Shots Total', scope: 'player' },
  { key: 'shots_on', label: 'Shots on Target', scope: 'player' },
  { key: 'passes_total', label: 'Passes Total', scope: 'player' },
  { key: 'key_passes', label: 'Key Passes', scope: 'player' },
  { key: 'pass_accuracy', label: 'Pass Accuracy %', scope: 'player' },
  { key: 'tackles_total', label: 'Tackles', scope: 'player' },
  { key: 'interceptions', label: 'Interceptions', scope: 'player' },
  { key: 'duels_total', label: 'Duels Total', scope: 'player' },
  { key: 'duels_won', label: 'Duels Won', scope: 'player' },
  { key: 'dribbles_attempts', label: 'Dribbles Attempted', scope: 'player' },
  { key: 'dribbles_success', label: 'Dribbles Successful', scope: 'player' },
  { key: 'fouls_drawn', label: 'Fouls Drawn', scope: 'player' },
  { key: 'fouls_committed', label: 'Fouls Committed', scope: 'player' },
  { key: 'yellow_cards', label: 'Yellow Cards', scope: 'player' },
  { key: 'red_cards', label: 'Red Cards', scope: 'player' },
  { key: 'penalty_scored', label: 'Penalties Scored', scope: 'player' },
  { key: 'saves', label: 'Saves', scope: 'player' },
  { key: 'goals_conceded', label: 'Goals Conceded', scope: 'player' },
];

export const METRIC_TEMPLATES = {
  team: [
    { name: 'Attacking Strength', formula: '(goals_for_per_match * 3) + (total_shots * 0.1) + (expected_goals * 2)' },
    { name: 'Defensive Stability', formula: '(clean_sheets * 3) - goals_against_per_match - (red_cards * 0.5)' },
    { name: 'Overall Power', formula: '(points * 2) + goal_difference + (win_rate * 100)' },
  ],
  player: [
    { name: 'Striker Score', formula: '(goals * 4) + assists + (shots_on * 0.5)' },
    { name: 'Playmaker Score', formula: '(assists * 3) + (key_passes * 1.5) + (pass_accuracy * 0.2)' },
    { name: 'Defensive Score', formula: '(tackles_total * 1.5) + interceptions + (duels_won * 0.5)' },
  ],
};
